# Generated by Django 4.1 on 2022-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
